/* Autogenerated by app_pll_model.py using command:
   /Users/ed/sandboxes/lib_sw_pll/python/sw_pll/pll_calc.py -i 24.0  -a -m 80 -t 12.288 -p 6.0 -e 5 -r --fracmin 0.695 --fracmax 0.905 --header
   Picked output solution #62
   Input freq: 24000000
   F: 203
   R: 1
   f: 3
   p: 4
   OD: 1
   ACD: 24
   Output freq: 12288000.0
   VCO freq: 2457600000.0 */

#define APP_PLL_CTL_REG  	0x0880CB01
#define APP_PLL_DIV_REG  	0x80000018
#define APP_PLL_FRAC_REG  	0x80000304
